import { Injectable } from '@angular/core';

import {
  Badge,
  BadgeRarity,
} from '../models/badge.model';

@Injectable({
  providedIn: 'root',
})
export class BadgeService {

  getBadges(): Badge[] {
    return [
      {
        id: 'primer-paso',
        name: 'Primer Paso',
        description: 'Completa tu primera aventura.',
        icon: '01-primer-paso.svg',
        rarity: 'common',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'caminante',
        name: 'Caminante',
        description: 'Recorre 5 km.',
        icon: '02-caminante.svg',
        rarity: 'uncommon',
        unlocked: false,
        progress: 0,
        target: 5,
      },
      {
        id: 'explorador',
        name: 'Explorador',
        description: 'Completa 5 aventuras.',
        icon: '03-explorador.svg',
        rarity: 'rare',
        unlocked: false,
        progress: 0,
        target: 5,
      },
      {
        id: 'ojo-curioso',
        name: 'Ojo Curioso',
        description: 'Descubre nuevos elementos durante tus rutas.',
        icon: '04-ojo-curioso.svg',
        rarity: 'rare',
        unlocked: false,
        progress: 0,
        target: 10,
      },
      {
        id: 'descubridor',
        name: 'Descubridor',
        description: 'Visita 10 lugares nuevos.',
        icon: '05-descubridor.svg',
        rarity: 'rare',
        unlocked: false,
        progress: 0,
        target: 10,
      },
      {
        id: 'amante-naturaleza',
        name: 'Amante de la Naturaleza',
        description: 'Completa 3 aventuras de naturaleza.',
        icon: '06-amante-naturaleza.svg',
        rarity: 'uncommon',
        unlocked: false,
        progress: 0,
        target: 3,
      },
      {
        id: 'explorador-cultural',
        name: 'Explorador Cultural',
        description: 'Completa 3 aventuras culturales.',
        icon: '07-explorador-cultural.svg',
        rarity: 'rare',
        unlocked: false,
        progress: 0,
        target: 3,
      },
      {
        id: 'cazador-atardeceres',
        name: 'Cazador de Atardeceres',
        description: 'Completa una aventura durante el atardecer.',
        icon: '08-cazador-atardeceres.svg',
        rarity: 'epic',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'noctambulo',
        name: 'Noctámbulo',
        description: 'Completa una aventura durante la noche.',
        icon: '09-noctambulo.svg',
        rarity: 'epic',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'gran-explorador',
        name: 'Gran Explorador',
        description: 'Completa 20 aventuras.',
        icon: '10-gran-explorador.svg',
        rarity: 'legendary',
        unlocked: false,
        progress: 0,
        target: 20,
      },
      {
        id: 'rutas-historicas',
        name: 'Rutas Históricas',
        description: 'Explora un lugar histórico.',
        icon: '11-rutas-historicas.svg',
        rarity: 'special',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'cerca-del-mar',
        name: 'Cerca del Mar',
        description: 'Completa una aventura cerca de la costa.',
        icon: '12-cerca-del-mar.svg',
        rarity: 'special',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'bajo-las-estrellas',
        name: 'Bajo las Estrellas',
        description: 'Completa una aventura nocturna especial.',
        icon: '13-bajo-las-estrellas.svg',
        rarity: 'special',
        unlocked: false,
        progress: 0,
        target: 1,
      },
      {
        id: 'campeche',
        name: 'Campeche',
        description: 'Explora un lugar emblemático de Campeche.',
        icon: '14-campeche.svg',
        rarity: 'special',
        unlocked: false,
        progress: 0,
        target: 1,
      },
    ];
  }
}